### PR TITLE
Legend font plus two bugfixes

### PR DESCRIPTION
**Pull request by Vindaar**
I accidentally sat on these changes on my local PC for months now and only realized now I never committed them.

This PR adds a `font` field to the `Legend` so that one can change the size / color / family of the `Legend` font.

And also fixes two stupid bugs of mine that would have been caught had I written tests for the sugar submodule. Sorry about that.

### CODE REVIEW

**Comment by brentp** [comment]
do you know what happened with travis? must be a change on their setup, unrelated to this.

**Comment by Vindaar** [comment]
Not sure what happened with travis. I'll see what I can do about it.

**Comment by Vindaar** [comment]
NOTE: the last commit is *NOT* ready to be merged! I need to clean stuff up and change some things here and there. Will probably only do that tomorrow though.

**Comment by Vindaar** [comment]
Ok, I just cleaned up that commit history.

I decided to change the following things:
- we now test against both the latest Nim stable and devel
- travis now uses `webview` to save images. I don't understand what's wrong with the previous approach to save images on travis and I'm not willing to waste anymore time to figure this out. Debugging travis is a pain.
- if travis uses `webview` or the user calls `saveImage` with the `webview` target, the `webview` window is automatically closed again after the file was successfully saved. This way there is a (strings attached...) way to automatically save many plots without as many tabs in a browser at least.

If this sounds reasonable I consider this ready to be merged.

**Comment by brentp** [comment]
cheers!

**Pull request merged**
